### PR TITLE
Force tasks with no files as failed

### LINKED ISSUE #90: Download email missing download links
This might be due to the user using dark mode (though I doubt it) but someone reported that their zimit download confirmation email looked like this

Image

### PR DESCRIPTION
**Pull request by benoit74**
Fix #90

### CODE REVIEW

**Review by rgaudin — CHANGES_REQUESTED** [review]
Haven't checked the template to find out what happens exactly but this with current line 133 is a mistake

```py
return MailToSend(status=SUCCESS, target=target, subject=subject, body=body)
```

**Comment by benoit74** [comment]
I don't get why? Because `status=SUCCESS`? This status is the hook return status, and this should be `SUCCESS` (and we should rename it for clarity ^^)

**Comment by rgaudin** [comment]
Please do so in this PR. This function used to return only on failures and only reach this point when everything's fine. Now that we get to this point with a failed task, we need to be more careful. We don't want to have to look at the templates to find this out

**Comment by benoit74** [comment]
> This function used to return only on failures and only reach this point when everything's fine.

Nope, this function already reached this point when task status was among "requested", "succeeded", "failed" or "canceled". See line https://github.com/openzim/zimit-frontend/blob/6eaea9254abaf6d075dc69d8996a62710fd74ec0/api/src/zimitfrontend/routes/utils.py#L109

But anyway, will fix this in this PR, better now than never

**Review by rgaudin — APPROVED** [review]

**Pull request merged**
