### PR TITLE
Update en.json to fix typos

### PR DESCRIPTION
**Pull request by Popolechien**
General copyediting.

### CODE REVIEW

**Review by benoit74 — COMMENTED** [review]
In general, it is probably way better, I do not have sufficient English level to assess this in details.

I'm however disturbed by the way we name the "final outcome". Sometimes we call it a `ZIM` (e.g. in `ZIM requested!`), sometimes a `zim file`, sometimes a `.zim file`.

On a personal basis, I tend to prefer `ZIM`, or `.zim file` if `ZIM` is too short / imprecise / confusing. I find that `ZIM file` is too long, `zim file` does not match our convention of using uppercase letters. `.zim file` looks a bit ugly to me (but it is the most precise one). And we must not forget this is going to be translated, so the simplest, the best from my PoV. 

@kelson42 any views to share on this?

**Comment by benoit74** [comment]
And is this the only fix needed regarding https://github.com/openzim/zimit-frontend/issues/93 or just "preparatory" work?

**Comment by Popolechien** [comment]
Not fully addressing #93, and yes I'm equally undecided on the .zim/ZIM thing.

**Comment by benoit74** [comment]
@kelson42 up, we need to make a decision on this wording and I know it is important for you if I'm not mistaken

**Comment by kelson42** [comment]
> @kelson42 up, we need to make a decision on this wording and I know it is important for you if I'm not mistaken

Thank you for asking, the answer is straight and there is only one: this is a "ZIM" file.

**Comment by benoit74** [comment]
@Popolechien can you update your PR accordingly (using `ZIM file` everywhere) or do you wanna help on this?

**Comment by Popolechien** [comment]
Alright, done. First time changing a PR here, so do make sure I did the right thing at the right place.

**Review by benoit74 — APPROVED** [review]

**Pull request merged**
